# Generated by Django 4.0.4 on 2022-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='prof',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
